### ISSUE TITLE
Control Tower Pipeline Detach SCP Action

### ISSUE THREAD

**Issue by sasiki-coder** [awslabs/aws-control-tower-customizations#41] opened 2020-11-06 19:49 UTC
Hi All,

Is Control Tower Pipeline perform the "Detach" SCP action from an OU/Account if we remove the code snippet from the manifest.yaml file?

For example,

Before: mainfest.yaml

organization_policies:
  - name: scp1
    description: test scp1
    policy_file: policies/scp1.json
   apply_to_accounts_in_ou:
    - OU1
    - OU2

The CT pipeline "ATTACH" scp1

update:mainfest.yaml

organization_policies:
  - name: scp2
    description: test scp2
    policy_file: policies/scp2.json
   apply_to_accounts_in_ou:
    - OU1
    - OU2

The CT pipeline "ATTACH" scp2, my expectation after update mainfest.yaml and "Detach" the scp1 from OU1,OU2 but it's not. Does control tower has that "Detach" capability?

Thanks, Sasi

**Comment by sasiki-coder** [comment] 2020-11-11 02:07
Please let us know if additional information needed, thanks

**Comment by groverlalit** [comment] 2020-12-07 21:09
Hello @sasiki-coder The SCP detach capability is not supported in the v1.2.1. Thanks.

**Comment by sasiki-coder** [comment] 2020-12-08 17:15
Okay Thanks for sharing.

**Comment by groverlalit** [comment] 2021-06-01 19:38
Duplicate of [#24](https://github.com/awslabs/aws-control-tower-customizations/issues/24)

**Closed** 2021-06-01 19:39 UTC
